version: '3.8'

services:
  producer:
    build: ./producer
    container_name: producer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - IDENTITY=producer-0
      - CONSUMERS_NAMES=consumer-0,consumer-1
    depends_on:
      consumer-0:
          condition: service_healthy
      consumer-1:
        condition: service_healthy

  consumer-0:
    build: ./consumer
    container_name: consumer-0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 2s
      retries: 60

  consumer-1:
    build: ./consumer
    container_name: consumer-1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: [ "CMD", "true" ]
      interval: 5s
      timeout: 2s
      retries: 60
